# Generated by Django 4.0.2 on 2022-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough', models.IntegerField()),
                ('fever', models.IntegerField()),
                ('sore_throat', models.IntegerField()),
                ('shortness_breath', models.IntegerField()),
                ('headache', models.IntegerField()),
                ('age60', models.IntegerField()),
                ('contact_with_positive', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('abroad', models.IntegerField()),
                ('classification', models.IntegerField()),
            ],
        ),
    ]
