# Generated by Django 4.0.2 on 2022-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidprediction',
            name='record_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
